spring:
  application:
    name: devopsTest
  datasource:
    url: jdbc:mysql://some-mysql:3306/devops_test?serverTimezone=Asia/Seoul
    username: ${username}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: none
