spring:
  application:
    name: devopsTest
  datasource:
    url: jdbc:mysql://localhost:3306/devops_test?serverTimezone=Asia/Seoul
    username: ${user}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: create

