spring:
  application:
    name: devopsTest
  datasource:
    url: jdbc:mysql://34.173.100.97:3307/devops_test?serverTimezone=Asia/Seoul
    username: ${username}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: none
